- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Update apt
    become: yes
    apt:
      update_cache: yes
  - name: Install nginx
    become: yes
    apt:
      name: nginx
      state: present